name: Deploy to Production

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Test
        run: |
          echo "${{ github.event.head_commit.message }}"
          echo "${GITHUB_SHA}"
      
      - name: Extract tag name
        id: extract_tag
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Print tag name
        run: echo "Tag Name is $TAG_NAME"

      - name: Do something with the tag
        run: |
          echo "Deploying version $TAG_NAME"